### ISSUE TITLE
URL Regex broken

### ISSUE THREAD

**Issue by Stephanevg** [ThePoShWolf/Curl2PS#1]
Hi @ThePoShWolf 

I have the following case which throws an error:

```powershell
$CurlCommand = @"
curl -X GET \
https://PlopServer/identity/api/tenants/Woopa/subtenants \
-H 'Accept: application/json' \
-H 'Authorization: Bearer {{token}}'
"@

ConvertTo-IRM -CurlString $CurlCommand
```

this is the error I get:

![image](https://user-images.githubusercontent.com/6302961/54704311-c530b200-4b3a-11e9-9784-9f9bf59f39b3.png)

I actually think have fixed the regex already (on line 13). 

The second thing that is a bit disturbing is the 'False' that we can see right above the `invoke-restMethod` output.

I'll push a PR with the regex fix shortly

Cheers

**Comment by ThePoShWolf** [comment]
Without digging into that much, that might also be related to the fact that it hasn't been set up to properly deal with multi-line strings for the ```$CurlString``` parameter.

I'm interested to see your fix!

**Comment by Stephanevg** [comment]
@ThePoShWolf PR is out! ;)
