### ISSUE TITLE
CurlCommand "Unknown Parameter: u. Cannot Continue"

### ISSUE THREAD

**Issue by rndadhdman** [ThePoShWolf/Curl2PS#28]
Trying to convert curl for netwrix to powershell. 
## curl command

$CurlString =@"
>> curl -H "Content-Type:application/xml; Charset=UTF-8"
>> https://tst-netwrix:10000/netwrix/api/v1/activity_records/search -u
>> Enterprise\NetwrixUser:NetwrixIsCool --data-binary @C:\APIdocs\Search.xml
>> "@

## Current Behavior

Error Message: 
ConvertTo-IRM: Cannot process argument transformation on parameter 'CurlCommand'. Cannot convert value "curl -H "Content-Type:application/xml; Charset=UTF-8"
https://tst-netwrix:10000/netwrix/api/v1/activity_records/search -u
Enterprise\NetwrixUser:NetwrixIsCool --data-binary @C:\APIdocs\Search.xml" to type "CurlCommand". Error: "Unknown parameter: u. Cannot continue."
## Your Environment

Powershell 7
```powershell
> $PSVersionTable
Name                           Value
----                           -----
PSVersion                      7.0.3
PSEdition                      Core
GitCommitId                    7.0.3
OS                             Microsoft Windows 10.0.18362
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

```powershell
> Get-Module Curl2PS
ModuleType Version    PreRelease Name                                ExportedCommands
---------- -------    ---------- ----                                ----------------
Script     0.0.3                 Curl2PS                             {ConvertTo-IRM, Get-CurlCommand, Get-URLData}
```

**Comment by ThePoShWolf** [comment]
I see what the issue is on this one. Should be a straightforward fix. Thanks for reporting that!

**Comment by midsimm** [comment]
@ThePoShWolf  any news on the fix as it  **https://was-jm.do.citrite.net/job/hydratest/build" to type "CurlCommand". Error: "Unknown parameter: user. Cannot continue**." Any update will be helpful. 
Thanks.

**Comment by mavaddat** [comment]
Simple workaround, detailed example from Make Your Own Ruby Gems [tutorial](https://guides.rubygems.org/make-your-own-gem/):

```pwsh
# curl -u qrush https://rubygems.org/api/v1/api_key.yaml > ~/.gem/credentials
$endpointURI = "https://rubygems.org/api/v1/api_key.yaml"  # example URI
$outPath = Resolve-Path "~/.gem/credentials"
$userName = "qrush"
$oneTimePasscode = 710223
Invoke-RestMethod -Credential ($cred =Get-Credential -UserName $userName) -Uri $endpointURI -Method Get -OutFile  $outPath -Headers @{"OTP"="$oneTimePasscode"}
```
