### ISSUE TITLE
Error: "Unknown parameter: 'ksX'. Cannot continue."

### ISSUE THREAD

**Issue by XiyongZhang** [ThePoShWolf/Curl2PS#35]
## Your Environment

```powershell
> $PSVersionTable

```

```powershell
> Get-Module Curl2PS

```

**Comment by XiyongZhang** [comment]
When I tried to use Curl2PS to convert a curl command which is something like "curl -ksX ......", it gave me an errro.

**Comment by ThePoShWolf** [comment]
Hi @XiyongZhang, can you provide the full curl command? Sanitized, of course.

It looks to me like `-ksX` is combining `-k` (`--insecure`), `-s` (`--silent`), and `-X` (`--request`). If that is the case, `-ksX` should be followed by the request method.

Also, if that is the case, then Curl2PS does not support this currently. It can certainly be done though.

**Comment by ThePoShWolf** [comment]
Ah, from the [man pages](https://www.man7.org/linux/man-pages/man1/curl.1.html):

> Short version options that don't need any additional values can
> be used immediately next to each other, like for example you can
> specify all the options -O, -L and -v at once as -OLv.

**Comment by ThePoShWolf** [comment]
v0.1.1 has been release that address the parameters that you reported on. Thanks for submitting the issue!
