### ISSUE TITLE
Consider / evaluate using PSStringScanner

### ISSUE THREAD

**Issue by Stephanevg** [ThePoShWolf/Curl2PS#8]
Hi@ThePoShWolf 

Since we are doing heavy regexing & always having to face 'lines of strings' in this module (this is an important detail actually) , perhaps we can have a look at this module from Doug finke.

[PsStringScanner](https://github.com/dfinke/PSStringScanner)

It looks like it could simplify how the parsing is done, and it would handled 'charcter per character'.

I can have a look in this / and / or we can work on this togther. But think it would be worth some time to analyze if this can be usefull, as I think the benefits could potentially be huge (On the simplification of the string analyzses of the Curl command).

Cheers

**Comment by ThePoShWolf** [comment]
Hey @Stephanevg I didn't notice this till now. My apologies! I've never used PsStringScanner before, I'll have to check it out 👍

**Comment by dfinke** [comment]
Let me know if I can help. String scanning is regex on steroids, happy to add to it if needed.

**Comment by ThePoShWolf** [comment]
Way delayed getting back to this one, I implemented a commandline parser instead. Thanks for the suggestion though!
